package libgdxpluginv01.constant;

public class Word {
	public static String PAGE_VISUAL_EDITOR = "Design";
	public static String PAGE_SOURCE_CODE = "Source";
	
	public static String ALIGN_CENTER = "Center";
	public static String ALIGN_LEFT = "Left";
	public static String ALIGN_RIGHT = "Right";
	public static String ALIGN_TOP = "Top";
	public static String ALIGN_BOTTOM = "Bottom";
	public static String ALIGN_TOP_LEFT = "Top left";
	public static String ALIGN_TOP_RIGHT = "Top right";
	public static String ALIGN_BOTTOM_LEFT = "Bottom left";
	public static String ALIGN_BOTTOM_RIGHT = "Bottom right";
	
	public static String PLAY_MODE_NORMAL = "Normal";
	public static String PLAY_MODE_REVERSE = "Reverse";
	public static String PLAY_MODE_LOOP = "Loop";
	public static String PLAY_MODE_LOOP_REVERSE = "Loop reverse";
	public static String PLAY_MODE_PING_PONG = "Ping pong";
	public static String PLAY_MODE_RANDOM = "Random";
	
	
	public static String PROPERTY_FIT = "Fit";
	public static String PROPERTY_FILL = "Fill";
	public static String PROPERTY_FILL_X = "Fill X";
	public static String PROPERTY_FILL_Y = "Fill Y";
	public static String PROPERTY_STRETCH = "Stretch";
	public static String PROPERTY_STRETCH_X = "Stretch X";
	public static String PROPERTY_STRETCH_Y = "Stretch Y";

	public static String PROPERTY_NAME = "Name";
	public static String PROPERTY_LOCATION = "Location";
	public static String PROPERTY_X = "x";
	public static String PROPERTY_Y = "y";
	public static String PROPERTY_SIZE = "Size";
	public static String PROPERTY_WIDTH = "width";
	public static String PROPERTY_HEIGHT = "height";
	public static String PROPERTY_VISIBLE = "Visible";
	
	public static String PROPERTY_EMPTY = "A property is not available.";
	public static String PROPERTY_DISABLE = "Disable";
	public static String PROPERTY_CHECK = "Check";
	public static String PROPERTY_STYLE = "Style";
	public static String PROPERTY_SET_STYLE = "Set style";
	public static String PROPERTY_TEXT = "Text";
	public static String PROPERTY_ALIGN = "Align";
	public static String PROPERTY_WRAP = "Wrap";
	public static String PROPERTY_ELLIPSIS = "Ellipsis";
	public static String PROPERTY_FONT_SCALE = "Font scale";
	public static String PROPERTY_MAX = "Max value";
	public static String PROPERTY_MIN = "Min value";
	public static String PROPERTY_STEP = "Step size";
	public static String PROPERTY_VALUE = "Init value";
	public static String PROPERTY_PAD = "Padding";
	public static String PROPERTY_PAD_LEFT = "Left";
	public static String PROPERTY_PAD_RIGHT = "Right";
	public static String PROPERTY_PAD_TOP = "Top";
	public static String PROPERTY_PAD_BOTTOM = "Bottom";
	public static String PROPERTY_ROTATION = "Rotation";
	public static String PROPERTY_FLIP = "Flip";
	public static String PROPERTY_COLOR = "Color";
	public static String PROPERTY_IMAGE = "Image";
	public static String PROPERTY_SET_COLOR = "Set color";
	public static String PROPERTY_SET_IMAGE = "Set image";
	public static String PROPERTY_SET = "Set";
	public static String PROPERTY_UP = "Up";
	public static String PROPERTY_DOWN = "Down";
	public static String PROPERTY_CHECKED = "Checked";
	public static String PROPERTY_DISABLED = "Disabled";
	public static String PROPERTY_OVER = "Over";
	public static String PROPERTY_CHECKED_OVER = "Checked over";
	public static String PROPERTY_FONT = "Font";
	public static String PROPERTY_FONT_COLOR = "Font color";
	public static String PROPERTY_DOWN_FONT_COLOR = "Down font color";
	public static String PROPERTY_OVER_FONT_COLOR = "Over font color";
	public static String PROPERTY_DISABLED_FONT_COLOR = "Disabled font color";
	public static String PROPERTY_CHECKED_FONT_COLOR = "Checked font color";
	public static String PROPERTY_CHECKED_OVER_FONT_COLOR = "Checked over font color";
	public static String PROPERTY_BACKGROUND = "Background";
	public static String PROPERTY_SCALING = "Scaling";
	public static String PROPERTY_NONE = "None";
	public static String PROPERTY_ORIGIN = "Origin";
	public static String PROPERTY_PLAY_MODE = "Play mode";
	public static String PROPERTY_FRAME_DURATION = "Time per frame";
	public static String PROPERTY_KEY_FRAMES = "Images";
	public static String PROPERTY_COUNT = "Count";
	public static String PROPERTY_FRAME = "Frame ";
	public static String PROPERTY_DISABLED_BACKGROUND = "Disabled background";
	public static String PROPERTY_KNOB = "Knob";
	public static String PROPERTY_DISABLED_KNOB = "Disabled knob";
	public static String PROPERTY_ON = "On";
	public static String PROPERTY_OFF = "Off";
	public static String PROPERTY_ON_DISABLED = "On disabled";
	public static String PROPERTY_OFF_DISABLED = "Off disabled";
	
	public static String OPEN = "Open";
	public static String CHOOSE_COLOR = "Choose a color";
	 
	public static String ERROR = "Error";
	public static String ERROR_INVALID_NAME = "Invalid name! Name must be not null, not start by number, not contain special chacracters: \"" + Parameter.SPECIAL_CHARACTER + "\"";
	public static String ERROR_INVALID_X = "X must be integer number.";
	public static String ERROR_INVALID_Y = "Y must be integer number.";
	public static String ERROR_INVALID_WIDTH = "Width must be integer number.";
	public static String ERROR_INVALID_HEIGHT = "Height must be integer number.";
	public static String ERROR_INVALID_COUNT = "Count must be integer number";
	public static String ERROR_INVALID_FONT_SCALE_X = "Font scale x must be float number";
	public static String ERROR_INVALID_FONT_SCALE_Y = "Font scale y must be float number";
	public static String ERROR_INVALID_PAD_RIGHT = "Pad right must be integer number";
	public static String ERROR_INVALID_PAD_LEFT = "Pad left must be integer number";
	public static String ERROR_INVALID_PAD_TOP = "Pad top must be integer number";
	public static String ERROR_INVALID_PAD_BOTTOM = "Pad bottom must be integer number";
	public static String LABEL_PROJECT_NAME = "Project Name";
	public static String LABEL_PROJECT_MAIN_PACKAGE = "Package";
	public static String LABEL_PROJECT_MAIN_CLASS = "Game class";
	public static String LABEL_PROJECT_DESTINATION_FOLDER = "Destination";
	public static String LABEL_BUTTON_BROWSE = "Browse";
	public static String LABEL_DESKTOP_PROJECT = "Desktop project";
	public static String LABEL_PROJECT_ANDROID_SDK_PATH = "Android SDK";
	public static String DEFAULT_PROJECT_NAME = "NewLibgdxGameProject";
	public static String DEFAULT_PROJECT_MAIN_PACKAGE="your.libgdx.project";
	public static String DEFAULT_PROJECT_MAIN_CLASS = "GameClass";
	public static String DEFAULT_PROJECT_DESTIONATION_FOLDER = "/home/superman/PluginExample";
	public static String WIZARD_PAGE_NAME = "libgdxProjctCreationWizardPage";
	public static String WIZARD_PAGE_TITLE = "Create new libgdx project";
	public static String WIZARD_PAGE_DESCRIPTION = "This wizard creates new libgdx project.";
}
